export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOADING_LOGIN = 'AUTH_LOADING_LOGIN';
export const AUTH_ERROR_LOGIN = 'AUTH_ERROR_LOGIN';
export const AUTH_SUCCESSFUL_LOGIN = 'AUTH_SUCCESSFUL_LOGIN';
export const TOKENS = 'TOKENS';
export const LOGOUT = 'LOGOUT';