export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOADING_LOGIN = 'AUTH_LOADING_LOGIN';
export const AUTH_ERROR_LOGIN = 'AUTH_ERROR_LOGIN';
export const AUTH_SUCCESSFUL_LOGIN = 'AUTH_SUCCESSFUL_LOGIN';
export const STORE_TOKEN = 'STORE_TOKEN';
export const ADMIN_STORE_TOKEN = 'ADMIN_STORE_TOKEN';
export const LOGOUT = 'LOGOUT';

export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const CONTACT_SUCCESSFUL = 'CONTACT_SUCCESSFUL';
